import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase start` — contains a bundled copy of the Supabase
    // edge runtime. Git ignores it via supabase/.gitignore, but ESLint has its
    // own ignore list, so without this every lint run reports ~150 errors in
    // minified third-party code.
    "supabase/.temp/**",
    // Playwright artefacts: traces, screenshots and the saved auth session.
    "test-results/**",
    "playwright-report/**",
    "blob-report/**",
    ".playwright/**",
    ".playwright-cli/**",
    ".playwright-mcp/**",
  ]),
]);

export default eslintConfig;
