-- ============================================================================
-- Baseline schema
-- ============================================================================
--
-- The complete current state of the database, in one file. Everything the
-- application depends on is created here: tables, the availability view, the
-- two functions, every RLS policy, every grant, indexes, storage
-- configuration, and the reference rows the admin panel expects to find.
--
-- HOW TO READ THIS FILE
--
-- Comments describe what each object is *for* and who is allowed to touch it.
-- They do not describe how it came to exist. Sixteen dated migrations, each
-- explaining the problem it solved, are kept verbatim in
-- `supabase/migrations-archive/` — that is where to look for the reasoning
-- behind a decision that looks strange.
--
-- WHAT THIS FILE IS NOT
--
-- It is not a change to production. Production already has this schema; this
-- is the file that lets `supabase db reset` rebuild it locally, and the one
-- place to read to find out what exists.
--
-- Every statement is idempotent — `if not exists`, `create or replace`, or a
-- `drop ... if exists` immediately before the create. Running it twice is a
-- no-op, which matters because an accidental run against a real database
-- should be boring.
--
-- ADDING SOMETHING NEW
--
-- Do not edit this file. Write a new dated migration, run it locally, then
-- apply it to production. See docs/DATABASE.md for the checklist — the step
-- people forget is the GRANT, and a missing grant has shipped a broken feature
-- here twice.
-- ============================================================================


-- ############################################################################
-- 1. ADMINISTRATORS
-- ############################################################################
--
-- First, because nearly every policy below calls is_admin(), and Postgres
-- resolves the function when the policy is created rather than when it runs.

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
-- The list of people allowed into /admin. One row per account.
--
-- This exists because `auth.role() = 'authenticated'` — the obvious way to
-- write an admin policy in Supabase — means only "is logged in at all", not
-- "is an administrator". Every policy on this schema therefore tests
-- `is_admin()` instead.
--
-- Nothing reaches this table through the public API, not even a logged-in
-- user: it is read exclusively by is_admin(), which runs with elevated
-- privileges. Locking it down here means a user cannot inspect or modify the
-- admin list even if a policy elsewhere is written incorrectly.
--
-- `on delete cascade` means deleting the auth account removes the admin rights
-- with it.
create table if not exists public.admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  email      text,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
revoke all on public.admins from anon, authenticated;

-- Note: administrators are not seeded here. Locally, supabase/seed.sql creates
-- the Playwright test admin. In production the row already exists, and adding
-- one is a deliberate act performed by hand.


-- ---------------------------------------------------------------------------
-- is_admin()
-- ---------------------------------------------------------------------------
-- "Is the person making this request on the admins list?" Called by nearly
-- every RLS policy in this file.
--
--   security definer  Runs as its creator rather than the caller. Required,
--                     because `admins` is revoked from everyone above — without
--                     it the function could not read the table it depends on.
--                     Also prevents infinite recursion, where a policy calls a
--                     function that triggers the same policy.
--
--   set search_path   Pins the schemas this function searches. Without it,
--                     someone able to create objects could define their own
--                     `admins` table in a schema searched first and have this
--                     function — which runs with elevated privileges — read
--                     theirs instead. Supabase's linter flags every SECURITY
--                     DEFINER function that omits this.
--
--   stable            The answer cannot change within one query, so Postgres
--                     calls it once rather than once per row. A meaningful
--                     speedup when a policy runs over a whole table.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admins where user_id = auth.uid()
  );
$$;

-- `revoke ... from public` first, and this is the important line. Postgres
-- grants EXECUTE to PUBLIC — the implicit group containing every role — when a
-- function is created, so revoking `anon` and `authenticated` by name leaves
-- them holding EXECUTE by inheritance. `pg_dump` does not print default PUBLIC
-- grants either, so the omission is invisible in a schema dump. That is how
-- register_for_event stayed callable by anyone for a month; see
-- migrations-archive/20260812000003_revoke_public_execute_on_functions.sql.
--
-- anon and authenticated genuinely need this one: RLS policy expressions are
-- evaluated with the caller's privileges, so any role reading a table with an
-- is_admin() policy must be able to execute it. It discloses nothing — it
-- answers only about the caller, and returns false for anyone anonymous.
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;


-- ############################################################################
-- 2. CORE TABLES
-- ############################################################################

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
-- Extra fields attached to a Supabase auth account.
--
-- Currently vestigial: the site has no public sign-up, only the instructor's
-- admin account, so nothing reads this table. It stays because
-- `registrations.user_id` and `testimonials.user_id` reference it, and dropping
-- it means dropping those foreign keys.
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  full_name  text,
  phone      text,
  avatar_url text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
  on public.profiles for select
  using ((select auth.uid()) = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using ((select auth.uid()) = id);


-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
-- A class, workshop or retreat. The central table: registrations, testimonials
-- and waiting-list entries all hang off it.
--
-- Bilingual columns follow the site-wide convention — `_ro` is required, `_en`
-- is optional and falls back to Romanian when blank.
--
-- `price` is a whole number in the major unit (150 means 150 RON, not 1.50).
-- Conversion to Stripe's minor units happens in one place, `lib/money.ts`.
--
-- `max_participants` NULL means unlimited. Zero and negative values are
-- rejected rather than treated as unlimited, because a capacity of zero is
-- indistinguishable from a full event and silently means nobody can book.
create table if not exists public.events (
  id                  uuid primary key default gen_random_uuid(),
  slug                text unique not null,
  title_ro            text not null,
  title_en            text,
  description_ro      text,
  description_en      text,
  date                date not null,
  time                time not null,
  location            text,
  price               integer not null default 0,
  currency            text not null default 'RON',
  max_participants    integer,
  image_url           text,
  whatsapp_group_link text,
  published           boolean default false,
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

-- The admin panel writes to PostgREST straight from the browser, so `min="0"`
-- on a form input is advice to the person typing, not a rule. These constraints
-- are the enforcement. A negative price would reach Stripe as a negative
-- charge; a non-positive capacity marks the whole calendar sold out.
alter table public.events drop constraint if exists events_price_non_negative;
alter table public.events add  constraint events_price_non_negative
  check (price >= 0);

alter table public.events drop constraint if exists events_capacity_positive;
alter table public.events add  constraint events_capacity_positive
  check (max_participants is null or max_participants > 0);

-- Four supported currencies, checked here because Stripe rejects an unknown
-- code at checkout — the worst possible moment to find out. Kept as a column
-- rather than a lookup table: four options that change roughly never.
alter table public.events drop constraint if exists events_currency_supported;
alter table public.events add  constraint events_currency_supported
  check (currency in ('RON', 'EUR', 'USD', 'GBP'));

alter table public.events enable row level security;

drop policy if exists "Anyone can view published events" on public.events;
create policy "Anyone can view published events"
  on public.events for select
  using (published = true);

drop policy if exists "Admins can manage events" on public.events;
create policy "Admins can manage events"
  on public.events for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- registrations
-- ---------------------------------------------------------------------------
-- One row per person signed up for an event. Holds names, email addresses and
-- phone numbers, so it is readable by administrators only.
--
-- Rows are created exclusively through `register_for_event()`, called from
-- /api/register with the service key. There is deliberately no public INSERT
-- path: the CAPTCHA, the input validation and the capacity check all live in
-- that route, and a direct write would skip all three.
--
-- `payment_status` drives capacity:
--   free       -- a free event, seat taken
--   pending    -- mid-checkout, holds the seat for one hour (see
--                 pending_hold_interval)
--   completed  -- paid, seat taken
--   refunded   -- no longer attending, seat released
create table if not exists public.registrations (
  id                uuid primary key default gen_random_uuid(),
  event_id          uuid not null references public.events(id) on delete cascade,
  user_id           uuid references public.profiles(id) on delete set null,
  full_name         text not null,
  email             text not null,
  phone             text not null,
  payment_status    text default 'free'
    check (payment_status in ('free', 'pending', 'completed', 'refunded')),
  stripe_session_id text,
  created_at        timestamptz default now()
);

alter table public.registrations enable row level security;

drop policy if exists "Admins can manage registrations" on public.registrations;
create policy "Admins can manage registrations"
  on public.registrations for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- blog_posts
-- ---------------------------------------------------------------------------
-- Articles. `published` is the instructor's switch; `hidden` is a separate
-- override used to pull a post without unpublishing it. The read policy checks
-- both, so a hidden post is not readable straight from the API either.
create table if not exists public.blog_posts (
  id         uuid primary key default gen_random_uuid(),
  slug       text unique not null,
  title_ro   text not null,
  title_en   text,
  content_ro text,
  content_en text,
  media_urls jsonb default '[]'::jsonb,
  published  boolean default false,
  hidden     boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.blog_posts enable row level security;

drop policy if exists "Anyone can view published posts" on public.blog_posts;
create policy "Anyone can view published posts"
  on public.blog_posts for select
  using (published = true and hidden is not true);

drop policy if exists "Admins can manage posts" on public.blog_posts;
create policy "Admins can manage posts"
  on public.blog_posts for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- testimonials
-- ---------------------------------------------------------------------------
-- Feedback from attendees, shown once an admin approves it. Submissions arrive
-- through /api/testimonials (service key + CAPTCHA), so there is no public
-- INSERT policy.
--
-- `rating` is nullable with no default on purpose. A default of 5 is how a site
-- ends up drawing five stars above every quote regardless of what anyone said;
-- NULL honestly means "not rated" and the page draws no stars at all.
create table if not exists public.testimonials (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references public.profiles(id) on delete cascade,
  event_id    uuid not null references public.events(id) on delete cascade,
  type        text not null check (type in ('text', 'video')),
  content     text not null,
  rating      smallint,
  author_name text,
  video_url   text,
  approved    boolean default false,
  created_at  timestamptz default now()
);

alter table public.testimonials drop constraint if exists testimonials_rating_range;
alter table public.testimonials add  constraint testimonials_rating_range
  check (rating is null or (rating >= 1 and rating <= 5));

alter table public.testimonials enable row level security;

drop policy if exists "Anyone can view approved testimonials" on public.testimonials;
create policy "Anyone can view approved testimonials"
  on public.testimonials for select
  using (approved = true);

drop policy if exists "Admins can manage testimonials" on public.testimonials;
create policy "Admins can manage testimonials"
  on public.testimonials for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- contact_messages
-- ---------------------------------------------------------------------------
-- Private correspondence from the contact form. Written by /api/contact with
-- the service key, read by administrators only — no public policy in either
-- direction.
create table if not exists public.contact_messages (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  email      text not null,
  subject    text,
  message    text not null,
  created_at timestamptz default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Admins can manage contact messages" on public.contact_messages;
create policy "Admins can manage contact messages"
  on public.contact_messages for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- email_templates
-- ---------------------------------------------------------------------------
-- The bodies of the transactional emails, editable from /admin/emails so the
-- instructor can reword them without a deploy. `{{placeholders}}` are
-- substituted by lib/email.ts.
--
-- One row per `type`, enforced by the unique constraint: the sending code looks
-- a template up by type and expects exactly one.
create table if not exists public.email_templates (
  id         uuid primary key default gen_random_uuid(),
  type       text unique not null
    check (type in ('registration_confirmation', 'payment_confirmation',
                    'testimonial_request', 'spot_available')),
  subject_ro text not null,
  subject_en text,
  body_ro    text not null,
  body_en    text,
  updated_at timestamptz default now()
);

alter table public.email_templates enable row level security;

drop policy if exists "Admins can manage email templates" on public.email_templates;
create policy "Admins can manage email templates"
  on public.email_templates for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ############################################################################
-- 3. WAITING LIST
-- ############################################################################

-- ---------------------------------------------------------------------------
-- waiting_list
-- ---------------------------------------------------------------------------
-- People who wanted a seat on a full event. When one frees up, the Stripe
-- webhook emails the next batch a claim link.
--
-- `notified_at` and `claim_expires_at` are what make a claim link checkable.
-- The entry's own id is the claim token, so without these two columns the
-- claim route cannot tell whether a link was ever issued or when it lapses —
-- and a link mailed in January would still work in August.
--
-- Letting a link lapse does not destroy the seat. The seat is genuinely free
-- and the event shows as bookable to everyone; the notification is a courtesy
-- head start, not a reservation.
create table if not exists public.waiting_list (
  id                      uuid primary key default gen_random_uuid(),
  event_id                uuid not null references public.events(id) on delete cascade,
  full_name               text not null,
  email                   text not null,
  phone                   text not null,
  created_at              timestamptz not null default now(),
  claimed_at              timestamptz,
  claimed_registration_id uuid references public.registrations(id) on delete set null,
  notified_at             timestamptz,
  claim_expires_at        timestamptz
);

alter table public.waiting_list enable row level security;

drop policy if exists "Admins can manage waiting list" on public.waiting_list;
create policy "Admins can manage waiting list"
  on public.waiting_list for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- waiting_list_notifications
-- ---------------------------------------------------------------------------
-- An audit log of which batch was emailed for which event, and when the batch's
-- links expired. Written by the Stripe webhook; nothing reads it except the
-- webhook itself, to work out the next `batch_number`.
--
-- The per-person expiry lives on `waiting_list` rather than here, because a
-- claim token identifies a person, not a batch.
create table if not exists public.waiting_list_notifications (
  id           uuid primary key default gen_random_uuid(),
  event_id     uuid not null references public.events(id) on delete cascade,
  batch_number integer not null,
  expires_at   timestamptz not null,
  spots_opened integer not null default 1,
  created_at   timestamptz not null default now()
);

alter table public.waiting_list_notifications enable row level security;

drop policy if exists "Admins can manage waiting list notifications" on public.waiting_list_notifications;
create policy "Admins can manage waiting list notifications"
  on public.waiting_list_notifications for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ############################################################################
-- 4. EDITABLE SITE CONTENT
-- ############################################################################

-- ---------------------------------------------------------------------------
-- site_content
-- ---------------------------------------------------------------------------
-- Page copy the instructor owns: hero headline, her biography, the portrait,
-- contact links. One row per piece of copy, addressed by `key`.
--
-- Key/value rather than a column per field, so adding a field is an INSERT
-- rather than a migration. The trade-off is honest: a typo in a key returns
-- nothing instead of failing loudly, which is why the expected keys are
-- declared in lib/site-content.ts and seeded below.
--
-- An empty `value_ro` means "not supplied yet" and the public pages render a
-- visible placeholder rather than an empty gap.
create table if not exists public.site_content (
  key        text primary key,
  value_ro   text not null default '',
  value_en   text,
  -- Groups fields under headings in the admin UI: 'about', 'home', 'general'.
  section    text not null default 'general',
  sort_order integer not null default 0,
  -- Chooses the admin editor: a single-line input, a textarea, or a media
  -- picker. Lets one screen edit every field without a hardcoded form.
  field_type text not null default 'text'
    check (field_type in ('text', 'richtext', 'image')),
  -- Shown above the input so she knows what she is filling in.
  label_ro   text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "Anyone can view site content" on public.site_content;
create policy "Anyone can view site content"
  on public.site_content for select
  using (true);

drop policy if exists "Admins can manage site content" on public.site_content;
create policy "Admins can manage site content"
  on public.site_content for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- faqs
-- ---------------------------------------------------------------------------
-- Practical questions shown on the events page. A table rather than more
-- site_content keys, because this is a list of variable length that needs
-- adding to and reordering — which key/value handles badly.
create table if not exists public.faqs (
  id          uuid primary key default gen_random_uuid(),
  question_ro text not null,
  question_en text,
  answer_ro   text not null,
  answer_en   text,
  sort_order  integer not null default 0,
  published   boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.faqs enable row level security;

drop policy if exists "Anyone can view published faqs" on public.faqs;
create policy "Anyone can view published faqs"
  on public.faqs for select
  using (published = true);

drop policy if exists "Admins can manage faqs" on public.faqs;
create policy "Admins can manage faqs"
  on public.faqs for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ---------------------------------------------------------------------------
-- whatsapp_links
-- ---------------------------------------------------------------------------
-- A small library of named WhatsApp invite URLs the instructor picks from when
-- creating an event, instead of retyping a 60-character link each time.
--
-- The event keeps its own `whatsapp_group_link` text column rather than
-- referencing a row here: the link is *copied* onto the event when chosen, so
-- deleting or editing a link later cannot rewrite what an attendee was already
-- told in their confirmation email.
--
-- Admin-only for reading as well as writing, which is unusual on this schema.
-- An invite URL is a capability — anyone holding it can join the group.
create table if not exists public.whatsapp_links (
  id         uuid primary key default gen_random_uuid(),
  -- What she calls it: "Grup general", "Retreat Apuseni". Shown in the picker.
  label      text not null,
  url        text not null,
  -- At most one link may be marked as the one to preselect on a new event.
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.whatsapp_links enable row level security;

drop policy if exists "Admins can manage whatsapp links" on public.whatsapp_links;
create policy "Admins can manage whatsapp links"
  on public.whatsapp_links for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());


-- ############################################################################
-- 5. CAPACITY: THE VIEW AND THE FUNCTION
-- ############################################################################
--
-- These two must agree. When the number a page displays and the rule the
-- booking button enforces disagree, you get the worst kind of bug: a page
-- offering seats next to a button that refuses them. The shared definition of
-- "does this registration hold a seat?" is:
--
--     not refunded, AND (not pending OR younger than pending_hold_interval)

-- ---------------------------------------------------------------------------
-- pending_hold_interval()
-- ---------------------------------------------------------------------------
-- How long an unpaid 'pending' registration may hold a seat.
--
-- Normally a seat comes back on its own: if the person never pays, Stripe fires
-- checkout.session.expired and the webhook deletes the row. But that only
-- happens if a Stripe session was ever created. Close the tab between
-- /api/register and /api/stripe/checkout and there is no session, so no expiry
-- event, so nothing ever releases the seat.
--
-- An hour, against Stripe sessions that expire in 30 minutes, leaves generous
-- room for the webhook to arrive first. Kept in a function so the view and
-- register_for_event() cannot drift apart.
create or replace function public.pending_hold_interval()
returns interval
language sql
immutable
set search_path = public, pg_temp
as $$ select interval '1 hour' $$;

revoke all on function public.pending_hold_interval() from public;
grant execute on function public.pending_hold_interval()
  to anon, authenticated, service_role;


-- ---------------------------------------------------------------------------
-- event_availability
-- ---------------------------------------------------------------------------
-- Public seat counts: an event id, its capacity, and how many seats are taken.
-- Nothing else.
--
-- The website cannot count `registrations` directly — that table holds names,
-- emails and phone numbers and is admin-only. A logged-out visitor querying it
-- gets back an empty result rather than an error, because RLS is a filter and
-- not a lock, so the count silently reads zero and every event looks empty
-- forever.
--
-- This view is how the count escapes that. It deliberately does NOT use
-- `security_invoker`: it runs with its creator's privileges, so it can read
-- registrations even though the caller cannot. That is safe here precisely
-- because it returns no row-level data — there is no column that could leak a
-- name or an email. Aggregation is the privacy boundary.
create or replace view public.event_availability as
select
  e.id               as event_id,
  e.max_participants as capacity,
  count(r.id)        as taken
from public.events e
left join public.registrations r
  on r.event_id = e.id
  -- Refunded people are not attending; their seat is free again.
  and r.payment_status <> 'refunded'
  -- A pending checkout holds its seat, but only for a bounded window.
  and (
    r.payment_status <> 'pending'
    or r.created_at > now() - public.pending_hold_interval()
  )
where e.published = true
group by e.id, e.max_participants;


-- ---------------------------------------------------------------------------
-- register_for_event()
-- ---------------------------------------------------------------------------
-- The only way a registration row is created.
--
-- It exists to close a race condition. Counting registrations and then
-- inserting, as two steps in application code, means two people submitting at
-- the same moment both count 14, both decide there is room, and both insert —
-- and you have 16 people in a room for 15. No amount of JavaScript fixes that,
-- because the gap between the count and the insert is where the bug lives.
--
-- Inside one function, both steps run in a single transaction and `FOR UPDATE`
-- on the event's row makes the second caller wait for the first. Sequential
-- rather than simultaneous. The lock is per row, so bookings for other events
-- are unaffected.
--
-- Returns JSONB: either {"success": true, "id": ...} or {"error": "..."} with a
-- message already in Romanian, ready to show the visitor.
create or replace function public.register_for_event(
  p_event_id UUID,
  p_full_name TEXT,
  p_email TEXT,
  p_phone TEXT,
  p_payment_status TEXT DEFAULT 'free'
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_max_participants INTEGER;
  v_published        BOOLEAN;
  v_current_count    INTEGER;
  v_registration_id  UUID;
BEGIN
  -- Guard against a status the caller made up. The table has a CHECK covering
  -- these too; this returns clean JSON instead of a raw constraint violation.
  IF p_payment_status NOT IN ('free', 'pending', 'completed', 'refunded') THEN
    RETURN jsonb_build_object('error', 'Invalid payment status.');
  END IF;

  SELECT max_participants, published
    INTO v_max_participants, v_published
    FROM events
   WHERE id = p_event_id
     FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Evenimentul nu există.');
  END IF;

  -- Draft events are not bookable. The API checks this too, but a rule this
  -- important belongs next to the data as well.
  IF v_published IS NOT TRUE THEN
    RETURN jsonb_build_object('error', 'Evenimentul nu este disponibil.');
  END IF;

  -- Must match event_availability exactly. See the note above.
  SELECT COUNT(*)
    INTO v_current_count
    FROM registrations
   WHERE event_id = p_event_id
     AND payment_status <> 'refunded'
     AND (
       payment_status <> 'pending'
       OR created_at > now() - public.pending_hold_interval()
     );

  -- NULL capacity means unlimited, so the check is skipped entirely.
  IF v_max_participants IS NOT NULL AND v_current_count >= v_max_participants THEN
    RETURN jsonb_build_object('error', 'Evenimentul este complet.');
  END IF;

  INSERT INTO registrations (event_id, full_name, email, phone, payment_status)
  VALUES (p_event_id, p_full_name, p_email, p_phone, p_payment_status)
  RETURNING id INTO v_registration_id;

  RETURN jsonb_build_object('success', true, 'id', v_registration_id);
END;
$$;

-- Only the server-side key may call this. The website reaches it through
-- /api/register, which is where the CAPTCHA, the rate limiter and the input
-- validation live — letting the browser call it directly skips all three, and
-- `p_payment_status => 'completed'` would then book a paid event without paying.
--
-- `from public` is the line that does the work. Revoking anon and authenticated
-- by name is not sufficient and previously was not: both inherited EXECUTE from
-- the PUBLIC grant Postgres adds at creation time.
--
-- Asserted from the outside in tests/rpc-exposure.spec.ts, which calls the RPC
-- over HTTP with the publishable key and expects a refusal. Testing the grant
-- would prove the statement is spelled right; testing the endpoint proves the
-- door is shut.
revoke all on function public.register_for_event(UUID, TEXT, TEXT, TEXT, TEXT)
  from public;
revoke all on function public.register_for_event(UUID, TEXT, TEXT, TEXT, TEXT)
  from anon, authenticated;
grant execute on function public.register_for_event(UUID, TEXT, TEXT, TEXT, TEXT)
  to service_role;


-- ############################################################################
-- 6. GRANTS
-- ############################################################################
--
-- Postgres checks two separate things before letting a query through:
--
--   1. GRANT  -- may this role touch this table at all?
--   2. RLS    -- which rows may it touch?
--
-- Both must pass, and they fail differently: a missing grant is a hard
-- "permission denied", while RLS silently returns nothing. Two features here
-- shipped broken because the policy was written and the grant was not, so the
-- grants are declared in this file rather than clicked in the dashboard.
--
--   anon           a visitor who is not logged in (the public pages)
--   authenticated  a logged-in user (in practice: the instructor in /admin)
--   service_role   the secret server-side key used by API routes. Bypasses RLS
--                  entirely, which is why it must never reach the browser.

-- Start from nothing on everything that is not public content, so a grant
-- added by hand in the dashboard cannot survive a rebuild unnoticed.
revoke all on public.events                     from anon;
revoke all on public.blog_posts                 from anon;
revoke all on public.testimonials               from anon;
revoke all on public.registrations              from anon;
revoke all on public.contact_messages           from anon;
revoke all on public.waiting_list               from anon;
revoke all on public.waiting_list_notifications from anon;
revoke all on public.email_templates            from anon;

-- Not revoked here, and worth knowing why: Supabase's project setup runs
-- `alter default privileges in schema public grant all on tables to anon`, so
-- every table created since — whatsapp_links, site_content, faqs, profiles —
-- carries REFERENCES, TRIGGER, TRUNCATE and MAINTAIN for anon. Those are not
-- reachable through PostgREST, which only issues SELECT/INSERT/UPDATE/DELETE,
-- and no SELECT was ever granted, so the tables stay unreadable. It is the
-- default posture on every Supabase project; singling out one table would
-- diverge from production for no gain. The revokes above exist because those
-- tables previously had real grants that had to come off.

-- Visitors read published content and nothing else. Never a write: every
-- public form posts to an API route holding the service key, which is what
-- keeps the CAPTCHA and the validation mandatory.
grant select on public.events             to anon;
grant select on public.blog_posts         to anon;
grant select on public.testimonials       to anon;
grant select on public.site_content       to anon;
grant select on public.faqs               to anon;
grant select on public.event_availability to anon;

-- profiles is unused (no public sign-up) and its RLS restricts every row to
-- `auth.uid() = id`, so this grant reaches nothing. Recorded because production
-- has it and this file is meant to reproduce production exactly — revoking it
-- would be a change, not a transcription, and an unused table with a
-- self-referential policy is not where that risk is worth taking.
grant select on public.profiles to anon, authenticated;

-- Logged-in users get full CRUD at the grant level; the RLS policies above
-- still require is_admin() for every operation, so a non-admin account gets an
-- empty result rather than data.
grant select, insert, update, delete on public.events                     to authenticated;
grant select, insert, update, delete on public.blog_posts                 to authenticated;
grant select, insert, update, delete on public.testimonials               to authenticated;
grant select, insert, update, delete on public.registrations              to authenticated;
grant select, insert, update, delete on public.contact_messages           to authenticated;
grant select, insert, update, delete on public.email_templates            to authenticated;
grant select, insert, update, delete on public.waiting_list               to authenticated;
grant select, insert, update, delete on public.waiting_list_notifications to authenticated;
grant select, insert, update, delete on public.site_content               to authenticated;
grant select, insert, update, delete on public.faqs                       to authenticated;
grant select, insert, update, delete on public.whatsapp_links             to authenticated;
grant select                         on public.event_availability         to authenticated;

grant select, insert, update, delete on public.events                     to service_role;
grant select, insert, update, delete on public.blog_posts                 to service_role;
grant select, insert, update, delete on public.testimonials               to service_role;
grant select, insert, update, delete on public.registrations              to service_role;
grant select, insert, update, delete on public.contact_messages           to service_role;
grant select, insert, update, delete on public.email_templates            to service_role;
grant select, insert, update, delete on public.waiting_list               to service_role;
grant select, insert, update, delete on public.waiting_list_notifications to service_role;
grant select, insert, update, delete on public.site_content               to service_role;
grant select, insert, update, delete on public.faqs                       to service_role;
grant select, insert, update, delete on public.whatsapp_links             to service_role;

-- Every table grants to service_role, and for a while this view did not. The
-- symptom is `permission denied for view event_availability` from an API route
-- using the secret key, which reads like an RLS problem and is not one — the
-- service role bypasses RLS entirely, so the usual debugging instinct leads
-- nowhere. Safe to grant: the view exposes no personal data, and the service
-- role could already read the underlying table.
grant select on public.event_availability to service_role;


-- ############################################################################
-- 7. INDEXES
-- ############################################################################

create index if not exists idx_events_published_date
  on public.events (published, date);
create index if not exists idx_registrations_event
  on public.registrations (event_id);
create index if not exists idx_blog_posts_published
  on public.blog_posts (published);
create index if not exists idx_testimonials_approved
  on public.testimonials (approved);
create index if not exists idx_testimonials_event
  on public.testimonials (event_id);

create index if not exists idx_waiting_list_event
  on public.waiting_list (event_id);
create index if not exists idx_waiting_list_claimed
  on public.waiting_list (claimed_at);
create index if not exists idx_waiting_list_email_event
  on public.waiting_list (event_id, email);
create index if not exists idx_wl_notifications_event
  on public.waiting_list_notifications (event_id);

-- Claims look an entry up by primary key and then test notified_at /
-- claim_expires_at, so the lookup needs no help. This one serves the admin view
-- of who is still waiting on a given event.
create index if not exists idx_waiting_list_event_unclaimed
  on public.waiting_list (event_id, claimed_at, created_at);

create index if not exists idx_faqs_published_order
  on public.faqs (published, sort_order);

-- At most one default link, enforced by a partial unique index rather than a
-- trigger. Setting a new default is "clear the old one, set the new one"; doing
-- it wrong fails loudly instead of leaving two defaults and a picker that has
-- to guess.
create unique index if not exists whatsapp_links_single_default
  on public.whatsapp_links (is_default)
  where is_default;


-- ############################################################################
-- 8. STORAGE
-- ############################################################################
--
-- One public bucket, `media`, holding photographs, audio and video for the blog
-- and the site content.

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

-- Uploads go browser -> Supabase directly, using a short-lived signed URL that
-- /api/upload issues after checking the caller is an admin. That path exists
-- because Vercel caps a serverless function's request body at 4.5 MB, which is
-- smaller than most phone video.
--
-- The consequence is that the browser never passes back through our code, so a
-- check written in the API route is only a suggestion. These limits are set on
-- the bucket so Supabase enforces them itself.
update storage.buckets
set
  file_size_limit = 52428800, -- 50 MB, matching what the admin UI promises
  allowed_mime_types = array[
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    -- image/svg+xml is deliberately absent: an SVG is XML and can contain
    -- <script>, so serving one from a public bucket is a stored-XSS vector.
    'audio/mpeg',
    'audio/wav',
    'audio/ogg',
    'audio/opus',
    'audio/webm',
    'audio/mp4',
    'audio/x-m4a',
    'audio/flac',
    'audio/aac',
    'video/mp4',
    'video/webm',
    'video/quicktime',
    'video/x-msvideo'
  ]
where id = 'media';

-- Scoped to `authenticated`, which governs *listing* only. Serving is
-- unaffected: requests to /storage/v1/object/public/media/... never consult
-- RLS — that is what makes a bucket public — so anonymous visitors load images
-- normally and simply cannot enumerate the bucket. The one thing that does need
-- to list is the admin media library, which runs in the browser under the
-- instructor's own session.
drop policy if exists "Anyone can view media files" on storage.objects;
drop policy if exists "Signed-in users can list media files" on storage.objects;
create policy "Signed-in users can list media files"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'media');

-- The admin media library (components/admin/media-library.tsx) lists and
-- deletes files from the browser with the logged-in user's own session, not
-- through an API route, so `authenticated` needs privileges on the storage
-- tables themselves. Without these the library comes back empty and the
-- Supabase dashboard shows the files sitting there perfectly fine.
grant select, insert, delete on storage.objects to authenticated;
grant select, insert, delete on storage.buckets to authenticated;


-- ############################################################################
-- 9. REFERENCE DATA
-- ############################################################################
--
-- Rows the application expects to exist. Not demo content — the admin panel
-- lists whatever is here, so seeding these keys is what makes the fields appear
-- for the instructor to fill in. `on conflict do nothing` throughout, so this
-- never overwrites something she has edited.

-- ---------------------------------------------------------------------------
-- Email templates
-- ---------------------------------------------------------------------------
insert into public.email_templates (type, subject_ro, body_ro, subject_en, body_en) values
('registration_confirmation',
 'Confirmare înscriere - {{event_name}}',
 '<h2>Salut {{user_name}}!</h2><p>Te-ai înscris cu succes la <strong>{{event_name}}</strong>.</p><p><strong>Data:</strong> {{event_date}}<br><strong>Ora:</strong> {{event_time}}<br><strong>Locație:</strong> {{event_location}}</p><p>Alătură-te grupului de WhatsApp: <a href="{{whatsapp_link}}">{{whatsapp_link}}</a></p><p>În fișierul atașat găsești invitația în calendar.</p>',
 'Registration confirmation - {{event_name}}',
 '<h2>Hi {{user_name}}!</h2><p>You have successfully registered for <strong>{{event_name}}</strong>.</p><p><strong>Date:</strong> {{event_date}}<br><strong>Time:</strong> {{event_time}}<br><strong>Location:</strong> {{event_location}}</p><p>Join the WhatsApp group: <a href="{{whatsapp_link}}">{{whatsapp_link}}</a></p><p>Find the calendar invitation attached.</p>'),

-- Carries the date, time, location and WhatsApp link. An earlier version of
-- this template had none of them and told the reader to look in the attached
-- calendar file, which does not contain them — so whoever paid received less
-- information than whoever booked a free event.
('payment_confirmation',
 'Confirmare plată - {{event_name}}',
 '<h2>Salut {{user_name}}!</h2><p>Plata pentru <strong>{{event_name}}</strong> a fost confirmată. Ne vedem acolo!</p><p><strong>Data:</strong> {{event_date}}<br><strong>Ora:</strong> {{event_time}}<br><strong>Locație:</strong> {{event_location}}</p><p>Alătură-te grupului de WhatsApp: <a href="{{whatsapp_link}}">{{whatsapp_link}}</a></p><p>În fișierul atașat găsești invitația pentru calendar.</p>',
 'Payment confirmation - {{event_name}}',
 '<h2>Hi {{user_name}}!</h2><p>Your payment for <strong>{{event_name}}</strong> is confirmed. See you there!</p><p><strong>Date:</strong> {{event_date}}<br><strong>Time:</strong> {{event_time}}<br><strong>Location:</strong> {{event_location}}</p><p>Join the WhatsApp group: <a href="{{whatsapp_link}}">{{whatsapp_link}}</a></p><p>The calendar invitation is attached.</p>'),

('testimonial_request',
 'Părerea ta contează - {{event_name}}',
 '<h2>Salut {{user_name}}!</h2><p>Ne-ar face plăcere să aflăm părerea ta despre <strong>{{event_name}}</strong>.</p><p>Lasă un testimonial aici: <a href="{{testimonial_link}}">{{testimonial_link}}</a></p>',
 'Your opinion matters - {{event_name}}',
 '<h2>Hi {{user_name}}!</h2><p>We would love to hear your feedback about <strong>{{event_name}}</strong>.</p><p>Leave a testimonial here: <a href="{{testimonial_link}}">{{testimonial_link}}</a></p>'),

-- Sent by the Stripe webhook when a seat frees up on a full event. Its
-- placeholders differ from the others: {{claim_url}} and {{expires_at}} rather
-- than the event date and location. `expires_at` arrives already formatted in
-- Romania's timezone, so the deadline shown is the one the claim route enforces.
('spot_available',
 'S-a eliberat un loc - {{event_name}}',
 '<h2>Salut {{user_name}}!</h2><p>S-a eliberat un loc la <strong>{{event_name}}</strong> și îți revine ție primul.</p><p><a href="{{claim_url}}">Rezervă-ți locul</a></p><p>Linkul este valabil până la {{expires_at}}. După această oră locul devine disponibil pentru toată lumea.</p>',
 'A spot opened up - {{event_name}}',
 '<h2>Hi {{user_name}}!</h2><p>A spot has opened up for <strong>{{event_name}}</strong>, and you are first in line.</p><p><a href="{{claim_url}}">Claim your spot</a></p><p>This link is valid until {{expires_at}}. After that the spot is offered to everyone.</p>')
on conflict (type) do nothing;


-- ---------------------------------------------------------------------------
-- Site content keys
-- ---------------------------------------------------------------------------
-- Seeded empty. Nothing here invents facts about the instructor — the public
-- pages render a visible placeholder for an empty value, which is the honest
-- behaviour and the reason the previous hardcoded "10+ years, 500+ classes,
-- 1000+ students" is not carried over.
insert into public.site_content (key, section, sort_order, field_type, label_ro, value_ro, value_en) values
  ('home.hero_title',       'home',    10, 'text',     'Titlu principal (pagina de start)', '', ''),
  ('home.hero_subtitle',    'home',    20, 'text',     'Subtitlu',                          '', ''),
  ('home.hero_image',       'home',    30, 'image',    'Fotografie principală',             '', null),
  ('home.intro',            'home',    40, 'richtext', 'Scurtă prezentare (2-3 fraze)',     '', ''),

  ('about.title',           'about',   10, 'text',     'Titlu pagina "Despre mine"',        '', ''),
  ('about.portrait',        'about',   20, 'image',    'Portret',                           '', null),
  ('about.body',            'about',   30, 'richtext', 'Povestea ta',                       '', ''),
  ('about.credentials',     'about',   40, 'richtext', 'Formare și certificări',            '', ''),

  ('contact.instagram_url', 'general', 10, 'text',     'Link Instagram',                    '', null),
  ('contact.email',         'general', 20, 'text',     'Email public',                      '', null)
on conflict (key) do nothing;


-- ############################################################################
-- ############################################################################
-- 10. OBJECT DESCRIPTIONS
-- ############################################################################
--
-- Descriptions for every table, view, function and non-obvious column are
-- stored in the database itself, where Supabase's Table Editor shows them.
--
-- They live in `20260812000002_object_comments.sql` rather than here, because
-- production carried only five of them when this baseline was taken and the
-- other twenty-five are a change rather than a transcription. This file
-- reproduces production; changes to it go in dated migrations alongside.
